### ISSUE TITLE
Unknown custom element: <v-icon> - did you register the component correctly

### ISSUE THREAD

**Issue by jeanfre777** [MatheusrdSantos/vue-quick-chat#15]
I get this message after installing via npm, and trying the example code you provide.

Unknown custom element: <v-icon> - did you register the component correctly

Thanks

**Comment by MatheusrdSantos** [comment]
Hi, @jeanfre777!
Could you post here the exact steps to reproduce the error?
I'll try to reproduce and solve the error in the next few days.
Thanks for reporting the error.

**Comment by jeanfre777** [comment]
Hi,
I installed this package with NPM (npm install vue-quick-chat --save) in one of my existing Vue projects.  I tried to use the component in one of my views, and I got the error.  I did not tried anything else.  Thank you !

**Comment by MatheusrdSantos** [comment]
I tried to reproduce the error in a new project on my computer but without success.
I guess the problem is happening because v-icon was moved to dev dependencies. So I don't know whether the problem is happening only with you (because of a specific problem) or it is a general problem.
The second case can be easily solved by me adding v-icon to project dependencies.

**Comment by MatheusrdSantos** [comment]
In case you still facing this problem I can try to reproduce the error in another machine.
So, if I found it, I'll add 'v-icon' to project dependencies.

Thanks again.
