### ISSUE TITLE
send image in chat

### ISSUE THREAD

**Issue by Tehsseen** [MatheusrdSantos/vue-quick-chat#22]
i am using your template it awsome but sir can i use image in chat kinldy guide how to achieve this. thanks
regards
Tahseen ullah

**Comment by MatheusrdSantos** [comment]
Hi, @Tehsseen! This functionality wasn't implemented yet.
I have plans to implement it at the end of this month or even next month.

Thanks for your feedback!

**Comment by Tehsseen** [comment]
ok  thank you @MatheusrdSantos   will wait for it.

**Comment by martinandersen3d** [comment]
Hi @MatheusrdSantos What is the status? :-) Going to a customer meeting this week :D 

Can I help in any way?

**Comment by MatheusrdSantos** [comment]
Hi, @martinandersen3d!
I haven't started development yet.
These are some insights that I have about this functionality, just in case you want to implement it:
- set a new message property: ```'type': 'image'```;
- this message type requires an URL to display the image;
- the chat is responsible for selecting the image from the computer and executes a callback (new prop to the component) called 'onImageSelected'. Since this is a prop, the implementation is up to the user. You won't implement it, just call it and use the response;
- this callback should receive the image as a parameter, upload it to the server and return the image URL;
- after that, the component receives the URL from the callback and update the URL property of the message;
- You also need to create a button to call the window that selects the image from the computer.

**Comment by MatheusrdSantos** [comment]
I'm currently implementing this functionality. If you want to follow the progress, you can check out this branch [send-images](https://github.com/MatheusrdSantos/vue-quick-chat/tree/send-images)

**Comment by martinandersen3d** [comment]
niiiice :-) Looking forward to it ;-)

I really like the 'api' you have planned :-)

![giphy](https://user-images.githubusercontent.com/19984581/76665478-48d38200-6588-11ea-976b-b34fc9f4b8c8.gif)

**Comment by vonec** [comment]
since you are doing something related to images, can you add support to have an optional avatar / profile images for participants

```
this.myself = {
          id: this.user.uid,
          name: this.user.name
          avatar: "IMAGEURL"
}
```

**Comment by MatheusrdSantos** [comment]
Hi, @vonec!
Yes, that's a good idea. I'll first release the images upload and then start the implementation of avatar images.

Thanks for your suggestion.

**Comment by MatheusrdSantos** [comment]
This functionality is available now.
Just update to version 1.1.0

**Comment by vonec** [comment]
thanks a lot, @MatheusrdSantos,  while you are at it, can you add support to read reciepts, similar to how have support to uploaded message single tick. now double tick

**Comment by MatheusrdSantos** [comment]
Hi, @vonec. Are you talking about to display visual feedback when the message is viewed like in a Whatsapp chat?

**Comment by vonec** [comment]
Yup exactly

**Comment by MatheusrdSantos** [comment]
Hi, @vonec. Now you can display profile pictures and display visual feedback when the image is viewed.
Just update to version 1.1.1 and read the documentation.
