### ISSUE TITLE
No close and hide functions.

### ISSUE THREAD

**Issue by albay13** [MatheusrdSantos/vue-quick-chat#3]
This is a good plugin, However, there is no close and toggle hide functionality.

**Comment by MatheusrdSantos** [comment]
Hy, @albay13! Thanks for your feedback.
I didn't implement this functionality yet because I'd like to let the component behave either with or without a toggle button. However, in a future implementation I will create a new component with this feature, e.g. '<ToggleChat>'.

**Comment by Arnaldoeloi** [comment]
I agree.

**Comment by Tofandel** [comment]
That's not the point, the point is there is a button but no prop/event for the close button (at least documented)

**Comment by MatheusrdSantos** [comment]
Hi, @Tofandel! That is really a problem. Thanks for your feedback.
I forgot to implement a way of passing an event to the closing button (that one with an 'X'). However, I will fix this problem as you suggest: 
- Changing the slot to scoped
- Adding an event prop for the button
About the problem with feather lib, I dont know yet if it's really necessary remove it, because in future implementations other icons can be needed.

Feels free to fork this project and implement those fixes.

**Comment by Tofandel** [comment]
I already did https://github.com/MatheusrdSantos/vue-quick-chat/pull/4 ;)
You can have a look at the test index.html I edited it

**Comment by MatheusrdSantos** [comment]
I accepted your pull request.
I guess the problem was solved, so I will close this issue.
@Tofandel, Thanks again!
